apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4= # base64 encoded 'admin'
  mongo-root-password: c2FwYW5h # base64 encoded 'sapana'
  mongo-uri: bW9uZ29kYjovL2FkbWluOnNhcGFuYUBtb25nby1zZXJ2aWNlOjI3MDE3Lwo= # base64 encoded 'mongodb://admin:sapana@mongo-service:27017/'
